### ISSUE TITLE
Périmètre fonctionnel

### ISSUE THREAD

**Issue by benel** [UTT-GL03/JobLinker#1]
Merci pour le premier livrable (choix du sujet, utilité sociale, impact de la numérisation) qui est plutôt bien.
Attention cependant, vous parlez de réseaux sociaux professionnels mais vous n'abordez jamais les fonctionnalités réellement liées aux liens entre les gens (faire suivre une annonce, recommander une personne, attester d'une compétence, etc.). 
Vous n'êtes pas du tout obligés de garder ces fonctionnalités, mais ça mériterait de l'expliciter car ça implique des périmètres fonctionnels assez différents.

**Comment by paulineSaur** [comment]
Monsieur, merci pour votre retour. Nous avons modifié la secteur "Impact numérique" en prenant en compte vos suggestions. Pourriez-vous nous faire un second retour s'il vous plaît? 
Merci.
